config/routes.rb
Charas::Application.routes.draw do
  root :to => "news#index"

  match "news" => "news#index", :as => :news
  match "news/:id" => "news#show", :as => :news
  match "news/:id/new_comment" => "news#new_comment", :via => :post, :as => :new_news_comment
  match "news/comment/:id/update" => "news#update_comment", :via => :post, :as => :edit_news_comment
  match "news/comment/:id/destroy" => "news#destroy_comment", :via => :delete, :as => :news_comment_destroy

  devise_for :users

  match "profile/:id" => "profiles#show", :as => :user_profile

  match "resources/search" => "resources#search", :as => :resource_search
  match "resources/favorite/:id" => "resources#favorite", :as => :resource_favorite
  match "resources/unfavorite/:id" => "resources#unfavorite", :as => :resource_unfavorite
  match "resources/category/:id" => "resources#category", :as => :resource_category
  resources :resources

  resources :games
  namespace "games" do
    match ":id/screenshots" => "screenshots#index", :as => :screenshots
    match "screenshots/:id" => "screenshots#show", :as => :screenshots_show
    match "screenshots/:id/makelogo" => "screenshots#logo", :as => :screenshots_logo
    match ":id/screenshots/create" => "screenshots#create", :via => :post, :as => :screenshots_create
    match "screenshots/destroy/:id" => "screenshots#destroy", :via => :delete, :as => :screenshots_destroy
  end

  namespace "admin" do
    root :to => "home#index"
    resources :categories
    resources :users
    resources :front_page_news_items

    match "resources/" => "resources#index", :as => :resources
    match "resources/approve/:id" => "resources#approve", :via => :post, :as => :resources_approve
    match "resources/delete/:id" => "resources#delete", :via => :delete, :as => :resources_delete
  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_allowed_in_admin
  current_section :admin

  def index
    
  end

  def check_allowed_in_admin
    current_user.can_see_admin_tab?
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
  def admin_link_section(title, &block)
    render :partial => "admin/link_section", :locals => {:title => title, :links => capture(&block)}
  end
end

app/views/admin/home/index.html.haml
= main_box("Admin Panel", "adminPanel") do
  .columns
    .column.left
      - if current_user.is_admin?
        = admin_link_section("Users") do
          %li= link_to("Users", admin_users_path)
      - if current_user.is_news_editor?
        = admin_link_section("News") do
          %li= link_to("Front Page News", admin_front_page_news_items_path)
    .column.right
      = admin_link_section("Complete Resources") do
        - if current_user.can_approve_resources?
          %li= link_to("Approve Resources", admin_resources_path)
        - if current_user.is_admin?
          %li= link_to("Categories", admin_categories_path)
  .clear