config/routes.rb
Charas::Application.routes.draw do
  root :to => "news#index"

  match "news" => "news#index", :as => :news
  match "news/:id" => "news#show", :as => :news
  match "news/:id/new_comment" => "news#new_comment", :via => :post, :as => :new_news_comment
  match "news/comment/:id/update" => "news#update_comment", :via => :post, :as => :edit_news_comment
  match "news/comment/:id/destroy" => "news#destroy_comment", :via => :delete, :as => :news_comment_destroy

  devise_for :users

  match "profile/:id" => "profiles#show", :as => :user_profile

  match "resources/search" => "resources#search", :as => :resource_search
  match "resources/favorite/:id" => "resources#favorite", :as => :resource_favorite
  match "resources/unfavorite/:id" => "resources#unfavorite", :as => :resource_unfavorite
  match "resources/category/:id" => "resources#category", :as => :resource_category
  resources :resources

  resources :games
  namespace "games" do
    match ":id/screenshots" => "screenshots#index", :as => :screenshots
    match "screenshots/:id" => "screenshots#show", :as => :screenshots_show
    match "screenshots/:id/makelogo" => "screenshots#logo", :as => :screenshots_logo
    match ":id/screenshots/create" => "screenshots#create", :via => :post, :as => :screenshots_create
    match "screenshots/destroy/:id" => "screenshots#destroy", :via => :delete, :as => :screenshots_destroy
  end

  namespace "admin" do
    root :to => "home#index"
    resources :categories
    resources :users
    resources :front_page_news_items

    match "resources/" => "resources#index", :as => :resources
    match "resources/approve/:id" => "resources#approve", :via => :post, :as => :resources_approve
    match "resources/delete/:id" => "resources#delete", :via => :delete, :as => :resources_delete
  end

end

app/views/resources/_category_link.html.haml
%li
  - if category_link.is_parent?
    .parent= category_link.name
    %ul.sub.navigation
      = render :partial => "category_link", :collection => category_link.children.sorted_alphabetically
  - else
    = link_to(category_link.name, resource_category_path(category_link.id))

app/views/resources/_favorite_button.html.haml
- if ResourceFavorite.is_favorite?(current_user.id, resource.id)
  = link_to(image_tag("delete.png") + " Unfavorite", resource_unfavorite_path(resource.id), :class => "button")
- else
  = link_to(image_tag("add.png") + " Favorite", resource_favorite_path(resource.id), :class => "button")

app/views/resources/_form.html.haml
- semantic_form_for @resource, :html => {:multipart => true} do |f|
    - f.inputs do
        = f.input :name
        = form_grouped_select(:resource, :category_id, Category.visible.roots, :children, :name, :id, :name)
        = f.input :res, :as => :file
        = f.input :description, :input_html => {:rows => 5}
    - f.buttons do
        = submit_button("#{image_tag("tick.png")} Submit")

app/views/resources/_resource_list.html.haml
= main_box(title) do
  - if !resources.empty?
    %ul.resourceList
      = render :partial => "res_list_item", :collection => resources
    .clear
    - if paginate
      = will_paginate resources
  - else
    %p No resources found.

app/views/resources/_resources_sidebar.html.haml
- if user_signed_in?
  .block
    %h3 My Resources
    %ul.navigation
      %li= link_to("Upload New Resource", new_resource_path)
.block
  %h3 Categories
  %ul.navigation
    = render :partial => "category_link", :collection => @sidebar_categories

app/views/resources/_row.html.haml
%tr
    %td= image_tag(row.res.url(:small))
    %td= link_to(row.name, row)
    %td= row.user.name
    %td= row.category.name
    %td

app/views/resources/_search_form.html.haml
- semantic_form_for @search, :url => resource_search_path, :html => { :method => :get, :class => "res_search" }  do |f|
  - f.inputs "Basic" do
    = f.input :query
  - f.inputs "Advanced" do
    = f.input :category_id, :as => :select, :collection => Category.visible.leafs, :group_by => :parent, :group_association => :children
  .clear
  - f.buttons do
    = submit_button("#{image_tag("magnifier.png")} Search")

app/views/resources/category.html.haml
= resource_list(@category.name, @resources)

= content_for :sidebar do
  = render "resources_sidebar"

app/views/resources/edit.html.haml
.block
    %h2 Edit Resource
    .content
        = render "form"

app/views/resources/index.html.haml
= main_box("Search") do
  = render "search_form"

= resource_list("Popular Resources", @popular_resources)

= content_for :sidebar do
  = render "resources_sidebar"

app/views/resources/new.html.haml
.block
    %h2 Upload New Resource
    .content
        = render "form"

app/views/resources/search.html.haml
= main_box("Search") do
  = render "search_form"

= resource_list("Search Results", @resources, true)

= content_for :sidebar do
  = render "resources_sidebar"

app/views/resources/show.html.haml
= main_box(@resource.name) do
  .resource
    = show_resource(@resource)
  .navform.wat-cf
    = favorite_button(@resource)
    = button_link(image_tag("icons/sm/disk.png") + " Download", @resource.res.url)
  %ul.list
    = list_item("Author", @resource.user.name)
    = list_item("Category", category_breadcrumb(@resource.category))
    = list_item("Favorites", @resource.fans.length)
    = list_item("Approved by", @resource.reviewer.name)
    = list_item("Description") do
      :markdown
        #{@resource.description}

= content_for :sidebar do
  - if user_signed_in? && current_user.is_admin?
    .block
      %h3 Admin
      %ul.navigation
        %li= link_to("Edit this Resource", edit_resource_path(@resource))
        %li= link_to("Delete this Resource", resource_path(@resource), :method => :delete, :confirm => "WARNING: This will delete the resource permanently. Are you sure?")
  = render "resources_sidebar"